config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "static_pages#top"
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'

  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]
  resources :post_icons do
    collection do
      get :post_icon_likes
    end
  end
  resources :created_icons do
    collection do
      get :created_icon_likes
    end
  end
  resources :created_icon_likes, only: %i[create destroy]
  resources :post_icon_likes, only: %i[create destroy]
  resources :icons, only: %i[index]
  resources :like_icons, only: %i[index]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # 管理画面用
  namespace :admin do
    root 'dashboards#index'
    resources :users
    resources :post_icons
    resources :created_icons
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
  end
end

app/models/post_icon.rb
class PostIcon < ApplicationRecord
  belongs_to :user
  has_one_attached :icon do |attachable|
    attachable.variant :display, resize_to_limit: [200, 200]
  end
  validates :title, presence: true
  validates :icon, presence: true
  has_many :post_icon_likes, dependent: :destroy

  validates :icon, content_type: { in: %w[image/jpeg image/gif image/png image/webp],
                                      message: "must be a valid icon format" },
                      size:         { less_than: 5.megabytes,
                                      message: "should be less than 5MB" }
  enum status: { published: 0, unpublished: 1 }
end

app/controllers/admin/post_Icons_controller.rb
class Admin::PostIconsController < Admin::BaseController
  before_action :set_post_icon, only: %i[edit update destroy]
  def index
    # N+1問題対策
    @post_icons = PostIcon.includes(:user).order("created_at DESC").page(params[:page]).per(10)
  end

  def edit; end

  def update
    if @post_icon.update(post_icon_params)
      flash[:success] = "投稿アイコンを更新しました。"
      redirect_to admin_post_icons_path
    else
      flash.now['error'] = "投稿アイコンの編集に失敗しました。"
      render :edit
    end
  end

  def destroy
    @post_icon.destroy!
    flash[:error] = "投稿アイコンを削除しました。"
    redirect_to admin_post_icons_path, status: :see_other
  end

  private

  def set_post_icon
    @post_icon = PostIcon.find(params[:id])
  end

  def post_icon_params
    params.require(:post_icon).permit(:title, :icon, :status)
  end
end

app/controllers/post_icons_controller.rb
class PostIconsController < ApplicationController
  before_action :set_posticon, only: %i[edit update destroy]

  def show
    @posticon= PostIcon.find(params[:id])
  end

  def new
    @posticon = PostIcon.new
  end

  def edit; end

  def create
    @posticon = current_user.post_icons.build(posticon_params)
    @posticon.icon.attach(params[:post_icon][:icon])
    result = Vision.image_analysis(params[:post_icon][:icon])
    if result
      if @posticon.save
        flash[:success] = "アイコンを投稿しました"
        redirect_to post_icon_url(@posticon)
      else
        flash.now[:error] = "アイコンの投稿に失敗しました"
        render :new, status: :unprocessable_entity
      end
    else
      flash.now[:error] = "不適切の画像です"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @posticon.update(posticon_params)
      flash[:success] = "投稿を編集しました"
      redirect_to post_icon_path(@posticon)
    else
      flash.now[:error] = "編集に失敗しました"
      render icons_url
    end
  end

  def destroy
    @posticon.destroy!
    redirect_to icons_path, status: :see_other
  end

  private

    def set_posticon
      @posticon = current_user.post_icons.find(params[:id])
    end

    def posticon_params
      params.require(:post_icon).permit(:title, :icon, :status)
    end
end

app/views/admin/post_icons/_post_icon.html.erb
<tr>
  <th><%= post_icon.id %></th>
  <td><%= post_icon.title %></td>
  <td><%= post_icon.status %></td>
  <td><%= image_tag post_icon.icon.variant(resize: '70x70').processed %></td>
  <td><%= post_icon.user.name %></td>
  <td>
    <%= link_to "編集", edit_admin_post_icon_path(post_icon), class: 'btn btn-sm' %>
  </td>
  <td>
    <%= link_to "削除", admin_post_icon_path(post_icon), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？"}, class: 'btn btn-sm' %>
  </td>
</tr>

app/views/admin/post_icons/edit.html.erb
<div class="m-5">
  <div class="w-full p-6 m-auto bg-slate-50 rounded-md shadow-md lg:max-w-lg">
    <h1 class="text-3xl font-semibold text-center">アイコンの編集</h1>
    <div class ="items-center åm-2">
  <%= form_with model: @post_icon, url: admin_post_icon_url(@post_icon), local: true do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title, class: 'w-full input input-bordered input-primary', required: true %>
    <div class='my-4 flex items-center justify-center'>
      <div class="mx-2 flex items-center">
        <%= form.radio_button :status, 'published', id: 'status_published', class: 'radio' %>
        <%= form.label :status_published, '公開', class: 'form-check-label' %>  
      </div>
      <div class="mx-2 flex items-center">
        <%= form.radio_button :status, 'unpublished', id: 'status_unpublished', class: 'radio' %>
        <%= form.label :status_unpublished, '非公開', class: 'form-check-label' %>
      </div>
    </div>
    <div class='my-4 flex items-center justify-center'>
      <%= image_tag @post_icon.icon.variant(resize: '300x300').processed %>
    </div>
    <div class="form-control mt-6 text-center">
      <%= form.submit class: 'btn btn-accent' %>
    </div>
  <% end %>
    </div>
  </div>
</div>

app/views/admin/post_icons/index.html.erb
<div class="overflow-x-auto">
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Status</th>
        <th>Icon</th>
        <th>User</th>
      </tr>
    </thead>
    <tbody>
      <%= render @post_icons %>
    </tbody>
  </table>
</div>
<div class="flex justify-center my-8">
  <%= paginate @post_icons %>
</div>