config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "static_pages#top"
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'

  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]
  resources :post_icons do
    collection do
      get :post_icon_likes
    end
  end
  resources :created_icons do
    collection do
      get :created_icon_likes
    end
  end
  resources :created_icon_likes, only: %i[create destroy]
  resources :post_icon_likes, only: %i[create destroy]
  resources :icons, only: %i[index]
  resources :like_icons, only: %i[index]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # 管理画面用
  namespace :admin do
    root 'dashboards#index'
    resources :users
    resources :post_icons
    resources :created_icons
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top privacy_policy terms_of_use]

  def top; end

  def privacy_policy; end

  def terms_of_use; end
end

app/views/static_pages/privacy_policy.html.erb
<section class="text-neutral">
  <div class="container px-5 pt-10 mx-auto bg-slate-50 rounded-md shadow-md">
    <div class="flex flex-wrap w-full mb-5 md:ml-10">
      <div class="lg:w-1/2 w-full mb-1 lg:mb-0">
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-theme">
          プライバシーポリシー
        </h1>
        <div class="h-1 w-20 bg-point rounded"></div>
      </div>
    </div>
    <div class="flex justify-center md:w-5/6 w-full px-5 mx-auto">
      <div>
        「A.Icon」（以下, 「本サイト」といいます。）は本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。<br>
        <br>
        <h2 class="text-xl">第1条（個人情報）</h2>
        「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。<br>
        <br>
        <h2 class="text-xl">第2条（個人情報の収集方法）</h2>
        本サイトは，ユーザーが利用登録をする際にニックネーム，生年月日，メールアドレスなどの個人情報をお尋ねすることがあります。<br>
        <br>
        <h2 class="text-xl">第3条（個人情報を収集・利用する目的）</h2>
        本サイトが個人情報を収集・利用する目的は，以下のとおりです。
        <br>
        ・本サイトサービスの提供・運営のため<br>
        ・ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）<br>
        ・メンテナンス，重要なお知らせなど必要に応じたご連絡のため<br>
        ・利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため<br>
        ・ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため<br>
        ・上記の利用目的に付随する目的<br>
        <br>
        <h2 class="text-xl">第4条（利用目的の変更）</h2>
        本サイトは，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。<br>
        利用目的の変更を行った場合には，変更後の目的について，本サイト所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。<br>
        <br>
        <h2 class="text-xl">第5条（個人情報の第三者提供）</h2>
        本サイトは，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。<br>
        ・人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき<br>
        ・公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき<br>
        ・国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき<br>
        ・予め次の事項を告知あるいは公表し，かつ本サイトが個人情報保護委員会に届出をしたとき<br>
          <div class="pl-3">
            1.利用目的に第三者への提供を含むこと<br>
            2.第三者に提供されるデータの項目<br>
            3.第三者への提供の手段または方法<br>
            4.本人の求めに応じて個人情報の第三者への提供を停止すること<br>
            5.本人の求めを受け付ける方法<br>
          </div>
        <br>
        <h2 class="text-xl">第6条（個人情報の開示）</h2>
        本サイトは，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。<br>
        ・本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合<br>
        ・本サイトの業務の適正な実施に著しい支障を及ぼすおそれがある場合<br>
        ・その他法令に違反することとなる場合<br>
        前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。<br>
        <br>
        <h2 class="text-xl">第7条（個人情報の訂正および削除）</h2>
        ユーザーは，本サイトの保有する自己の個人情報が誤った情報である場合には，本サイトが定める手続きにより，本サイトに対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。<br>
        本サイトは，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。<br>
        本サイトは，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。<br>
        <br>
        <h2 class="text-xl">第8条（個人情報の利用停止等）</h2>
        本サイトは，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。<br>
        前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。<br>
        本サイトは，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。<br>
        前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。<br>
        <br>
        <h2 class="text-xl">第9条（プライバシーポリシーの変更）</h2>
        本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。<br>
        本サイトが別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。<br>
        <br>
        <h2 class="text-xl">第10条（お問い合わせ窓口）</h2>
        本ポリシーに関するお問い合わせは，下記のお問い合わせ窓口までお願いいたします。<br>
        <br>
        以上
      </div>
    </div>
    <div class="mt-10 mx-3 flex flex-row justify-center">
      <%= link_to root_path, class: "btn mb-10" do %>
        トップページに戻る
      <% end %>
    </div>
  </div>
</section>

app/views/static_pages/terms_of_use.html.erb
<section class="text-neutral">
  <div class="container px-5 pt-10 mx-auto bg-slate-50 rounded-md shadow-md">
    <div class="flex flex-wrap w-full mb-5 md:ml-10">
      <div class="lg:w-1/2 w-full mb-1 lg:mb-0">
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-theme">
          利用規約
        </h1>
        <div class="h-1 w-20 bg-point rounded"></div>
      </div>
    </div>
    <div class="flex justify-center md:w-5/6 w-full px-5 mx-auto">
      <div>
        この利用規約（以下，「本規約」といいます。）は，A.Icon（以下，「運営者」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。<br>
        <br>
        <h2 class="text-xl">第1条（適用）</h2>
        本規約は，ユーザーと運営者との間の本サービスの利用に関わる一切の関係に適用されるものとします。<br>
        運営者は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。<br>
        本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。<br>
        <br>
        <h2 class="text-xl">第2条（利用登録）</h2>
        本サービスにおいては，登録希望者が本規約に同意の上，運営者の定める方法によって利用登録を申請し，運営者がこれを承認することによって，利用登録が完了するものとします。<br>
        運営者は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。<br>
        ・利用登録の申請に際して虚偽の事項を届け出た場合<br>
        ・本規約に違反したことがある者からの申請である場合<br>
        ・その他，運営者が利用登録を相当でないと判断した場合<br>
        <br>
        <h2 class="text-xl">第3条（ユーザーIDおよびパスワードの管理）</h2>
        ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。<br>
        ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。運営者は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。<br>
        ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，運営者に故意又は重大な過失がある場合を除き，運営者は一切の責任を負わないものとします。<br>
        <br>
        <h2 class="text-xl">第4条（禁止事項）</h2>
        ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。<br>
        ・法令または公序良俗に違反する行為<br>
        ・犯罪行為に関連する行為<br>
        ・本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為<br>
        ・運営者，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為<br>
        ・本サービスによって得られた情報を商業的に利用する行為<br>
        ・運営者のサービスの運営を妨害するおそれのある行為<br>
        ・不正アクセスをし，またはこれを試みる行為<br>
        ・他のユーザーに関する個人情報等を収集または蓄積する行為<br>
        ・不正な目的を持って本サービスを利用する行為<br>
        ・本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為<br>
        ・他のユーザーに成りすます行為<br>
        ・運営者が許諾しない本サービス上での宣伝，広告，勧誘，または営業行為<br>
        ・面識のない異性との出会いを目的とした行為<br>
        ・運営者のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為<br>
        ・その他，運営者が不適切と判断する行為<br>
        <br>
        <h2 class="text-xl">第5条（本サービスの提供の停止等）</h2>
        運営者は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。<br>
        ・本サービスにかかるコンピュータシステムの保守点検または更新を行う場合<br>
        ・地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合<br>
        ・コンピュータまたは通信回線等が事故により停止した場合<br>
        ・その他，運営者が本サービスの提供が困難と判断した場合<br>
        運営者は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。<br>
        <br>
        <h2 class="text-xl">第6条（利用制限および登録抹消）</h2>
        運営者は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。<br>
        ・本規約のいずれかの条項に違反した場合<br>
        ・登録事項に虚偽の事実があることが判明した場合<br>
        ・運営者からの連絡に対し，一定期間返答がない場合<br>
        ・本サービスについて，最終の利用から一定期間利用がない場合<br>
        ・その他，運営者が本サービスの利用を適当でないと判断した場合<br>
        運営者は，本条に基づき運営者が行った行為によりユーザーに生じた損害について，一切の責任を負いません。<br>
        <br>
        <h2 class="text-xl">第7条（退会）</h2>
        ユーザーは，運営者の定める退会手続により，本サービスから退会できるものとします。(退会手続きについてはサービス開発中となります。ご了承ください)<br>
        <br>
        <h2 class="text-xl">第8条（保証の否認および免責事項）</h2>
        ・運営者は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。<br>
        ・運営者は，本サービスに起因してユーザーに生じたあらゆる損害について、運営者の故意又は重過失による場合を除き、一切の責任を負いません。<br>
        ・前項ただし書に定める場合であっても，運営者は，運営者の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（運営者またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません<br>
        ・運営者は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。<br>
        <br>
        <h2 class="text-xl">第9条（サービス内容の変更等）</h2>
        運営者は，ユーザーへの事前の告知をもって、本サービスの内容を変更、追加または廃止することがあり、ユーザーはこれを承諾するものとします。<br>
        <br>
        <h2 class="text-xl">第10条（利用規約の変更）</h2>
        運営者は以下の場合には、ユーザーの個別の同意を要せず、本規約を変更することができるものとします。<br>
        ・本規約の変更がユーザーの一般の利益に適合するとき。<br>
        ・本規約の変更が本サービス利用契約の目的に反せず、かつ、変更の必要性、変更後の内容の相当性その他の変更に係る事情に照らして合理的なものであるとき。<br>
        運営者はユーザーに対し、前項による本規約の変更にあたり、事前に、本規約を変更する旨及び変更後の本規約の内容並びにその効力発生時期を通知します。<br>
        <br>
        <h2 class="text-xl">第11条（個人情報の取扱い）</h2>
        運営者は，本サービスの利用によって取得する個人情報については，本サイト「プライバシーポリシー」に従い適切に取り扱うものとします。<br>
        <br>
        <h2 class="text-xl">第12条（通知または連絡）</h2>
        ユーザーと運営者との間の通知または連絡は，運営者の定める方法によって行うものとします。運営者は,ユーザーから,運営者が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。<br>
        <br>
        <h2 class="text-xl">第13条（権利義務の譲渡の禁止）</h2>
        ユーザーは，運営者の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。<br>
        <br>
        <h2 class="text-xl">第14条（準拠法・裁判管轄）</h2>
        本規約の解釈にあたっては，日本法を準拠法とします。<br>
        本サービスに関して紛争が生じた場合には，運営者の本店所在地を管轄する裁判所を専属的合意管轄とします。<br>
        <br>
        以上
      <div>
    </div>
    <div class="mt-10 mx-3 flex flex-row justify-center">
      <%= link_to root_path, class: "btn mb-10" do %>
        トップページに戻る
      <% end %>
    </div>
  </div>
</section>

app/views/static_pages/top.html.erb
<div class="pb-6 sm:pb-8 lg:pb-12 mx-5">
  <div class="w-full p-6 m-auto bg-slate-50 rounded-md shadow-md  mt-5">
    <section class="flex flex-wrap ">
      <div class="container mx-auto flex md:mt-20 md:flex-row flex-col items-center">
      <!-- image - start -->
        <div class="flex items-center justify-center md:w-1/2 w-full h-80 overflow-hidden">
          <%= image_tag asset_path("top2.png", size: "250x250"), class:"max-w-full max-h-full" %>
        </div>
        <!-- image - end -->
        <!-- content - start -->
        <div class="md:w-1/2 flex flex-col text-left md:mx-5">
          <p class="py-1 px-1 whitespace-nowrap text-left">こういう時、ありませんか？</p>
          <div class="chat chat-start">
            <div class="chat-bubble">SNSのアイコン何にしよう...</div>
          </div>
          <div class="chat chat-end">
            <div class="chat-bubble">なんかいい写真ないな...</div>
          </div>
          <div class="text-l font-bold text-black sm:text-2xl mt-5">
          <span class="badge badge-accent badge-outline badge-lg mb-1">そんなあなたへ</span>
          <br/>
          生成AIで アイコン作成 お手伝いします。
          </div>
        </div>
        <!-- content - end -->
      </div>
    </section>
    <% if logged_in? %>
      <div class="text-center md:mb-10">
        <%= link_to 'アイコンを作る', new_created_icon_path,class:"btn btn-outline btn-secondary m-5"%>
        <%= link_to 'アイコンを投稿する', new_post_icon_path,class:"btn btn-outline btn-secondary m-5"%>
      </div>
    <% else %>
      <div class="text-center md:mb-10">
        <div class='inset-y-0 right-0"'>
            <label for="my_modal_1" class="btn btn-outline btn-secondary mt-5">ログイン/新規登録</label>
            <!-- Put this part before </body> tag -->
            <input type="checkbox" id="my_modal_1" class="modal-toggle" />
            <div class="modal" role="dialog">
              <div class="card bg-sky-50 flex flex-wrap justify-center">
                <div class="card bg-slate-50 rounded-md shadow-md mx-5 mt-5">
                  <div class="card-body items-center text-center">
                    <h2 class="card-title">新規登録</h2>
                    <p>初めてのご利用の方はこちらから</p>
                    <div class="card-actions justify-end">
                      <%= link_to '新規登録ページへ', new_user_path, class:"btn btn btn-outline btn-secondary mt-2"%>
                    </div>
                  </div>
                </div>
                <div class="card bg-slate-50 rounded-md shadow-md mx-5 mt-5">
                  <div class="card-body items-center text-center">
                    <h2 class="card-title">ログイン</h2>
                    <p>すでに登録済みの方はこちらから</p>
                    <div class="card-actions justify-end">
                      <%= link_to 'ログインページへ', login_path, class:"btn btn btn-outline btn-secondary mt-2"%>
                    </div>
                  </div>
                </div>

              <div class="modal-action">
                  <label for="my_modal_1" class="btn mb-2 mr-2 bg-slate-50 rounded-md shadow-md">Close</label>
              </div>
              </div>
            </div>
          </div>
        <div class="tooltip tooltip-open tooltip-bottom mb-5" data-tip="まずは">
          <label for="my_modal_2" class="btn btn-sm btn-ghost">お試し(ゲストログイン)</label>
            <!-- Put this part before </body> tag -->
            <input type="checkbox" id="my_modal_2" class="modal-toggle" />
            <div class="modal" role="dialog">
              <div class="card bg-sky-50 flex flex-wrap justify-center m-2">
                <div class="card bg-slate-50 rounded-md shadow-md mx-5 mt-5">
                  <div class="card-body items-center text-center">
                    <h2 class="card-title">お試し(ゲストログイン)</h2>
                    <p>お試しでご利用される方はこちらから
                      <br/>
                      全ての機能をご利用いただけます。
                    </p>
                    <div role="alert" class="alert alert-warning mt-2">
                      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                      <span>再度ログインできません。</span>
                    </div>
                    <div class="card-actions justify-end">
                      <%= link_to 'いますぐ試す', '/guest_login',class:"btn btn-outline btn-secondary mt-5", data: { turbo_method: :post } %>
                    </div>
                  </div>
                </div>
              <div class="modal-action">
                  <label for="my_modal_2" class="btn mb-2 mr-2 bg-slate-50 rounded-md shadow-md">Close</label>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>