config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "static_pages#top"
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'

  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]
  resources :post_icons do
    collection do
      get :post_icon_likes
    end
  end
  resources :created_icons do
    collection do
      get :created_icon_likes
    end
  end
  resources :created_icon_likes, only: %i[create destroy]
  resources :post_icon_likes, only: %i[create destroy]
  resources :icons, only: %i[index]
  resources :like_icons, only: %i[index]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # 管理画面用
  namespace :admin do
    root 'dashboards#index'
    resources :users
    resources :post_icons
    resources :created_icons
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
  end
end

app/views/shared/_before_login_header.html.erb
<header>
  <div class="navbar">
    <div class="flex-1">
      <%= link_to 'A.Icon', root_path, class: "btn btn-ghost text-3xl font-header_name" %>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal px-1 font-body_style">
        <li><%= link_to 'みんなのアイコン',  icons_path %></li>
        <li><%= link_to 'ログイン', login_path %></li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul class="mb-0">
    <% object.errors.each do |error| %>
      <div class="flash_message container mx-auto w-full">
        <div class="bg-red-100 border-red-400 text-red-700 py-2 my-2 rounded relative px-2" role="alert">
          <span class="block sm:inline">
            <%= error.full_message %>
          </span>
        </div>
      </div>
    <% end %>
  </ul>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-10 text-base-content rounded  flex flex-col items-center">
  <nav class="grid grid-flow-col gap-4">
    <%= link_to '利用規約',terms_of_use_path, class: "link link-hover"%>
    <%= link_to 'プライバシーポリシー',privacy_policy_path, class: "link link-hover"%>
    <%= link_to 'お問い合わせ', "https://twitter.com/takuywater", class: "link link-hover" %>
  </nav> 
  <aside>
    <p>Copyright © A.Icon </p>
  </aside>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="navbar">
    <div class="flex-1">
      <%= link_to 'A.Icon', root_path, class: "btn btn-ghost text-3xl font-header_name" %>
    </div>
    <div class="flex-none md:hidden">
      <div class="dropdown dropdown-end">
        <div tabindex="0" role="button" class="btn btn-ghost rounded-btn">
          <svg class="swap-off fill-current" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 512 512"><path d="M64,384H448V341.33H64Zm0-106.67H448V234.67H64ZM64,128v42.67H448V128Z"/></svg>
        </div>
        <ul tabindex="0" class="menu dropdown-content z-[1] p-2 shadow bg-base-100 rounded-box w-52 mt-4 font-body_style">
          <li><%= link_to 'アイコンAI生成', new_created_icon_path %></li>
          <li><%= link_to 'アイコンの保存', new_post_icon_path %></li>
          <li><%= link_to 'みんなのアイコン', icons_path %></li>
        </ul>
      </div>
      <div class="dropdown dropdown-end">
          <div tabindex="0" role="button" class="btn btn-ghost rounded-btn">
            <% if current_user.current_icon.attached?%>
              <div class="avatar">
                <div class="w-8 rounded-full ring ring-success ring-offset-base-100 ring-offset-2">
                    <%= image_tag current_user.current_icon %>
                </div>
              </div>
            <% else %>  
              <div class="avatar placeholder">
                <div class="bg-neutral text-neutral-content rounded-full ring ring-success w-8">
                  <span class="text-[0.5rem]"><%=current_user.name%></span>
                </div>
              </div>
            <% end %> 
          </div>
          
          <ul tabindex="0" class="menu dropdown-content z-[1] p-2 shadow bg-base-100 rounded-box w-52 mt-4 font-body_style">
            <li><%= link_to 'マイページ', profile_path %></li>
            <li><%= link_to 'お気に入りのアイコン', like_icons_path(current_user) %></li>
            <li><%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete }  %></li>
          </ul>
        </div>
    </div>
    <div class="hidden md:block">
      <ul class="menu menu-horizontal px-1 items-center py-0 font-body_style">
        <li><%= link_to 'アイコンAI生成', new_created_icon_path %></li>
        <li><%= link_to 'アイコンの保存', new_post_icon_path %></li>
        <li><%= link_to 'みんなのアイコン', icons_path %></li>
        <div class="dropdown dropdown-end">
          <div tabindex="0" role="button" class="btn btn-ghost rounded-btn">
            <% if current_user.current_icon.attached?%>
              <div class="avatar">
                <div class="w-8 rounded-full ring ring-success ring-offset-base-100 ring-offset-2">
                    <%= image_tag current_user.current_icon.variant(resize: '70x70').processed %>
                </div>
              </div>
            <% else %>  
              <div class="avatar placeholder">
                <div class="bg-neutral text-neutral-content rounded-full ring ring-success w-8">
                  <span class="text-[0.5rem]"><%=current_user.name%></span>
                </div>
              </div>
            <% end %> 
          </div>
          <ul tabindex="0" class="menu dropdown-content z-[1] p-2 shadow bg-base-100 rounded-box w-52 mt-4 font-body_style">
            <li><%= link_to 'マイページ', profile_path %></li>
            <li><%= link_to 'お気に入りのアイコン', like_icons_path(current_user) %></li>
            <li><%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete }  %></li>
          </ul>
        </div>
      </ul>
    </div>
  </div>
</header>